# Status bar
set-option -g status-position top

# Status update interval
set -g status-interval 1

# Basic status bar colors
set -g status-style fg=blue,bg=brightblack

# Left side of status bar
set -g status-left-style fg=blue,bg=brightblack
set -g status-left-length 40

# set -g status-left " 🔥 [#S] #[fg=brightgreen]#{@separator_session_name} #[fg=yellow]#I #[fg=white]#{@main_separator} #[fg=cyan]#P "
set -g status-left " [#S] 🍂 #[fg=yellow]#I #[fg=white]#{@main_separator} #[fg=cyan]#P "

# Right side of status bar
set -g status-right-style fg=cyan,bg=brightblack
set -g status-right-length 40

# needed: go get -u github.com/arl/gitmux
# set -g status-right ' #(gitmux "#{pane_current_path}") '
set -g status-right '#{prefix_highlight} #[fg=green]%a %d/%m #[fg=white]#{@main_separator} #[fg=yellow]%H:%M '

# Window status
set -g window-status-format "  #I:#W#F  "
set -g window-status-current-format "  #I:#W#F  "

# Window style
set -g window-status-style fg=white,bg=brightblack
set -g window-status-current-style fg=black,bg=white

# Window with activity status
set -g window-status-activity-style fg=brightblack,bg=yellow

# Window separator
set -g window-status-separator ""

# Window status alignment
set -g status-justify left

# Pane border
set -g pane-border-style fg=brightblack,bg=default
set -g pane-active-border-style fg=brightblack,bg=default

# Pane number indicator
set -g display-panes-colour red
set -g display-panes-active-colour magenta

# Clock mode
set -g clock-mode-colour red
set -g clock-mode-style 24

# Message
set -g message-style fg=black,bg=red

# Command message
set -g message-command-style fg=default,bg=default

# Mode
set -g mode-style fg=default,bg=red

